version: '3.9'

services:
  backend:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: student
      POSTGRES_DB: incubator
    volumes:
      - .dbdata:/var/lib/postgresql/data
